### ISSUE TITLE
Артефакты с контактными площадками SMD компонентов, установленных не под прямым углом

### ISSUE THREAD

**Issue by DannyColdburn** [XRay3D/GERBER_X3#101]
При загрузке гербер файла возникают артефакты с контактными площадками SMD компонентов, которые установлены не под прямым углом.
Проблема касается контактных площадок с формой Rounded Rectangle и Oval.
![image](https://github.com/XRay3D/GERBER_X3/assets/55917400/0c4e8ae5-cece-4c71-90bd-a0e78ad4164c)

**Comment by XRay3D** [comment]
Файл приложите. А то оно 100500 вариантов может использовать для форммирования этих прощадок.

**Comment by Maximych** [comment]
А что с этими площадками?
[Gerber_TL-kontroler_PCB_TL-kontroler_2_2024-03-08.zip](https://github.com/XRay3D/GERBER_X3/files/14537078/Gerber_TL-kontroler_PCB_TL-kontroler_2_2024-03-08.zip)

**Comment by XRay3D** [comment]
Добавлю в копилку тестов. Макрос неправильно разбирается.
