### ISSUE TITLE
если есть возможность добавь инструмент маркер (в принципе это тоже самое что фрезеровка но как бы что бы отдельный инструмент был)

### ISSUE THREAD

**Issue by ivan64435** [XRay3D/GERBER_X3#106]
если есть возможность добавь инструмент маркер (в принципе это тоже самое что фрезеровка но как бы что бы отдельный инструмент был)

**Comment by XRay3D** [comment]
Не понял вопрос. Можно как-то развёрнуто?

**Comment by ivan64435** [comment]
https://www.youtube.com/watch?v=CvrLKwXLOZQ

**Comment by XRay3D** [comment]
А чем фреза не устраивает? Скорость погружения задираете до небес, и будет опускаться как по G0.

**Comment by ivan64435** [comment]
ok
