### ISSUE TITLE
[FR] gerber reload

### ISSUE THREAD

**Issue by whoim2** [XRay3D/GERBER_X3#107]
Привет! В качестве мелочи приятной можно было бы добавить пункт "перегрузить файл с диска", как в слайсерах, помогло бы мне вот сейчас сэкономить силы :)

Спасибо за программу! Лучшее что есть в этой сфере.

**Comment by XRay3D** [comment]
Она спрашивает перезагрузку при изменении гербера по тому-же пути и имени..

**Comment by whoim2** [comment]
> Она спрашивает перезагрузку при изменении гербера по тому-же пути и имени..

Проверю, спасибо.
