### ISSUE TITLE
Hi. This is not a problem but it is still a problem!

### ISSUE THREAD

**Issue by DANmodify** [XRay3D/GERBER_X3#109]
Eng: I tried your software and it's great, it's smoother than I thought it would be. Thank you for creating this software.
I have an idea for you, I need to make a 2 layer PCB. When I need to switch layers, I need positioning holes. Can you add them to your software. I look forward to your response.
Vietnamese: Tôi đã thử trải nghiệm phần mềm của bạn và nó rất tuyệt vời, nó mượt mà hơn những gì tôi nghĩ. Cảm ơn bạn đã tạo ra phần mềm này.
Tôi có một ý tưởng cho bạn, tôi cần làm PCB 2 layer. Khi cần chuyển layer tôi cần lỗ định vị. Bạn có thể thêm chúng vào phần mềm của bạn không. Tôi rất mong sự phản hồi từ bạn

**Comment by ronindev** [comment]
It already has position holes. It calls refpoints. To produce gcode for them use double-right-click on them 
![image](https://github.com/XRay3D/GERBER_X3/assets/921324/c8120aeb-972e-4c38-8fc0-7f185c66bc99)
