### ISSUE TITLE
Инструмент штриховка не генерирует G-code при выводе УП

### ISSUE THREAD

**Issue by inscrut** [XRay3D/GERBER_X3#115]
Добавил текст, выбираю штриховку, она отобразилась, трек линии есть, то есть как бы сработало все
Экспортирую УП, на выходе треков нет, только шапка и концовка, пример:

`;	              Name: Ўтриховка внутри_L-D0.1MM
;	              Tool: Ћазер (O0.1 mm)
;	    Tool passDepth: 0
;	     Tool stepover: 0.05
;	Tool feedRate mm/s: 33.3333
;	             Depth: 0.1
;	              Side: Top
G21 G17 G90
G0Z0
M5
X0Y0
M30
`

**Comment by XRay3D** [comment]
https://disk.yandex.ru/d/9VU4e4Jn_MCkBw тут крайние по идее рабочие. Но под форточки только.
