### ISSUE TITLE
Отменить принудительный рендеринг в режиме PocketR ради ускорения

### ISSUE THREAD

**Issue by Kurdl** [XRay3D/GERBER_X3#22]
При выборе шага растра 0.05мм и меньше программа уходит в долгий тайм-аут и не реагирует ни на что, пока не отрисует всё огромное количество линий растра.
Предлагаю сделать рендеринг по запросу пользователя. Т.е. чекбокс на панели фалов не взводить.

**Comment by XRay3D** [comment]
В режиме аппаратной отрисовки через OpenGL (искать в настройках) у меня без проблем даже 0,01 нормально отрисовывает.
