### ISSUE TITLE
Баг при разбиение Вороного.

### ISSUE THREAD

**Issue by iMaks-RS** [XRay3D/GERBER_X3#25]
Добрый день!

Опять вылез баг при разбиение Вороного.. один пад остался висеть в воздухе, отрезанный от все остальных. Проект не сохранил, т.к. спешил. ((( Использовал тестую версию G2G. Выгружал из диптрейс в весрию Gerber X2

**Comment by XRay3D** [comment]
Файлик бы не помешал, похоже диптрейс как то особенно генерит гербер и я его некорректно разбираю.

**Comment by iMaks-RS** [comment]
При импорте "потерялась" одна дорожка.. По всей видимости это и есть причина.. Потеря дорожки при импорте в G2G.. если этот момент не проверить.. то потом на плате приходится кидать перемычки (((
![lost trace](https://user-images.githubusercontent.com/35815614/89281400-b5900b80-d652-11ea-9c53-d75782ee74c7.JPG)

версии используемого ПО.  
![g2g version](https://user-images.githubusercontent.com/35815614/89281741-33ecad80-d653-11ea-9cf6-157643a0f53a.JPG)
![diptrace version](https://user-images.githubusercontent.com/35815614/89281748-35b67100-d653-11ea-8c14-0407a0ef0756.JPG)

если повторно импортировать файл - бага нет и дорожка появляется

[lan adapter.zip](https://github.com/XRay3D/GERBER_X2/files/5021469/lan.adapter.zip)

**Comment by lskramarov** [comment]
при импорте герберов сгенеренных в альтиуме тоже иногда, что то не прогружается, так же помогает повторный импорт.

**Comment by iMaks-RS** [comment]
> 
> 
> при импорте герберов сгенеренных в альтиуме тоже иногда, что то не прогружается, так же помогает повторный импорт.

Поставил самую актуальную на данный момент версию G2G, не тестовую, 784.  Проблема с пропажей дорожки при импорте ушла.  На версии 778 этот баг всегда появляется при первом же импорте гербера. Иногда приходилось раза по 3-4 открывать файл, пока не откроет без глюк ))) Альтиум не владею, но хочется.. т.к. модуль встроен во Fusion360..  Тогда всю подготовку к фрезеровке можно будет в одном софте делать )
