### ISSUE TITLE
Сделать нарезку ненужной меди на квадратики как альтернативу полной выборки

### ISSUE THREAD

**Issue by El-Engr** [XRay3D/GERBER_X3#30]
Свободная незаземленная медь между дорожками может стать причиной паразитных связей. Для ВЧ плат ее просто необходимо убирать, хотя это требует времени и ресурса гравера. Но проблему таких паразитных связей можно решить, нарезав медь на мелкие квадратики наподобие "Copper Thieving". Это значительно ускорит  изготовление платы и сохранит ресурс гравера. В принципе, достаточно разрешить устанавливать отступ больше, чем половина диаметра гравера, но специальный режим был бы весьма удобен.

**Comment by XRay3D** [comment]
Я подумаю над этим. Как это правильно обозвать.

**Comment by El-Engr** [comment]
Спасибо!
По-английски, наверное, правильно будет "Crosshatching" или "Copper crosshatching", ну или что-то подобное. Термин "Copper thieving" употреблять, думаю, не стоит, это делается для другой цели. По-русски выходит "Перекрестная насечка" или "Насечка свободной меди" и т.п.

**Comment by XRay3D** [comment]
![Снимок](https://user-images.githubusercontent.com/10693876/108636941-7d8ad180-7499-11eb-8ae5-20bd0cbaa07c.PNG)
Типа такого?

**Comment by El-Engr** [comment]
Да! Отлично!
