### ISSUE TITLE
0.8.0 preview (GGEasy_x32) и beta 0.8.0

### ISSUE THREAD

**Issue by YuryW** [XRay3D/GERBER_X3#37]
Выделенные элементы ПП с помощью Ctrl и мышки по цвету не отличаются от ещё не выделенных , что затрудняет этот этап работы.

**Comment by XRay3D** [comment]
> Выделенные элементы ПП с помощью Ctrl и мышки по цвету не отличаются от ещё не выделенных , что затрудняет этот этап работы.
А можно по подробнее? У меня всё работает, можно скриншот.

**Comment by YuryW** [comment]
Работает, только когда наводишь мышкой на выбранные компоненты, то есть можно посмотреть какие выбрал, обязательно наведя на них курсор. Как только курсор съезжает с элемента, цвет у всех становится одинаковым.

**Comment by YuryW** [comment]
Решение проблемы было в настройках видеокарты.
Цифровую интенсивность уменьшил со 100% до 50% и всё стало четко просматриваться.
Спасибо!

**Comment by XRay3D** [comment]
Никогда бы не догадался туда залезть.
