### ISSUE TITLE
Удаление конкретных булавок

### ISSUE THREAD

**Issue by LinFor** [XRay3D/GERBER_X3#41]
Хотелось бы возможность удалить конкретную булавку. Как уже писал выше - я вырезаю из g-кода руками сверловку первой булавки - отверстие под неё уже есть на столе, а на заготовке сверлю ручками.

From #32

**Comment by YuryW** [comment]
Сейчас уже есть такая возможность, но только если отверстия для булавок фрезеруются, а не сверлятся. После создания УП Булавки, она не сохраняется, выделяются мышкой с нажатой Ctrl отверстия под нужные далее для работы булавки, которые следует оставить, потом входим в УП Профиль - выставляем глубину отверстий под булавки, выбираем фрезу, Внутри, Создать, сохраняем далее только эту УП.

**Comment by XRay3D** [comment]
Выполнено в 0.8.0
