### ISSUE TITLE
ошибка в названии меню

### ISSUE THREAD

**Issue by calabr** [XRay3D/GERBER_X3#52]
Build 0.8.0.0  Mar 14 2021
В английском меню : Viev  - должно быть View

не ошибко, но режет глаз - пункт меню Paths - множественное число. Обычно принято использовать единственное число Path
Меню View -> Fit best - Обычно используют Best Fit, или Fit to screen
на булавке чекбокс "Used" - это "использованный" - должно быть "Use" или "In use"

**Comment by XRay3D** [comment]
Поправлю, английский учу по ходу написания :-)
