### ISSUE TITLE
редактирование формата сверловки

### ISSUE THREAD

**Issue by info69** [XRay3D/GERBER_X3#58]
При редактировании формата сверловки не сохраняется новое значение
![2021-08-19_11-43-54](https://user-images.githubusercontent.com/89187865/130038078-7011b3a9-15b6-4ad6-9900-daaff89dd9be.png)

**Comment by YuryW** [comment]
Это параметры для редактирования в текущем сеансе проекта .
А вот здесь они сохраняются.
![Параметры_сверловки - копия](https://user-images.githubusercontent.com/79474615/130349547-1a880ba8-d0a6-4e8b-a6f6-d46a5efb9813.jpg)

**Comment by info69** [comment]
Добрый день. В настройках нет вкладки excellon.
![2021-08-22_18-01-35](https://user-images.githubusercontent.com/89187865/130360079-e7b28531-8deb-4557-b3b8-0a1dbe984535.png)

**Comment by YuryW** [comment]
Следите за самыми свежими версиями среди тестовых. Это появилось с версии [0.8.0.2](https://disk.yandex.ru/d/L-laABnSVY4Ubw/0.8.0/0.8.0.2).
![версия_0 8 0 2 - копия](https://user-images.githubusercontent.com/79474615/130364569-9fcd4b8a-c5b5-48f4-a7f6-50c4b53fdfff.jpg)

**Comment by info69** [comment]
![2021-08-23_00-26-54](https://user-images.githubusercontent.com/89187865/130370580-56b649b5-2803-4084-b50b-e72123f2ef63.png)

**Comment by YuryW** [comment]
Это только часть программы.. Чтобы получить отдельно эту новую версию GGEasy, нужно сделать полную копию предыдущей и в ней заменить эти две папки и экзешник на новые:
![Версия_0 8 0 2_1 - копия](https://user-images.githubusercontent.com/79474615/130371421-662113b0-af65-495c-a28c-3c28ed62e0f6.jpg)
![Версия_0 8 0 2_2 - копия](https://user-images.githubusercontent.com/79474615/130371846-8cfbb26d-99f7-47ce-b6bc-5361d7b9dc5a.jpg)

На многие вопросы Вы найдёте ответы [тут](https://cnc-club.ru/forum/viewtopic.php?f=155&t=22277&view=unread#unread) и [тут](https://cnc3018.ru/threads/ggeasy-grber2gcode-frezerovka-pechatnyx-plat-na-chpu-zasvetka-lazerom-izuchaem-delimsja-opytom-i-dostizhenijami.2231/).

**Comment by info69** [comment]
Спасибо
