### ISSUE TITLE
Неправильное отображение при расстанвке мостиков.

### ISSUE THREAD

**Issue by calabr** [XRay3D/GERBER_X3#67]
**Versions**
 - GGEasy version: 0.8.1.0

**PC info**
- OS : Win10 x64

При расстановке мостиков для обработки по профилю значек мостика рисует с неправильной стороны от контура - при обрезке снаружи значек стави  внутри. 
 Программу потом строит правильно с мостиком в нужном месте.

**Comment by XRay3D** [comment]
Я думаю проще чтобы с двух сторн рисовало, направление исходных данных не всегда соответствует реально получаемому. Если отображать честно, то по затратам на установку и перемещение будет равносильно просчитыванию траектории на каждый чих мышкой.
