### ISSUE TITLE
Возможность отрицательного отступа

### ISSUE THREAD

**Issue by carrotFoxx** [XRay3D/GERBER_X3#73]
Добрый день, коллеги!

Есть ли возможность сделать допустимым установку отступа равной 0 или отрицательному значению, т.к. в случае с HLDI возможна "недозаливка" (см. скриншоты)

![Снимок](https://user-images.githubusercontent.com/46748053/152678951-c959ae2d-e231-4161-b294-fada84321fa7.PNG)
 
![изображение](https://user-images.githubusercontent.com/46748053/152678964-17a69b7c-aa4f-4bdf-9572-a392306da741.png)

**Comment by YuryW** [comment]
Добрый вечер!
Отступ (смещение) - это расстояние между двумя центрами соседних проходов лазера или фрезы. 10% отступа позволяет делать перекрытие площади освещения (фрезерования)  на 90% между двумя соседними проходами луча (фрезы). И это сейчас возможно выставить в HLDI. При нулевом отступе инструмент будет перемещаться бесконечно на одном месте. При отрицательном - изменит направление последовательного смещения на противоположное только лишь.
От края меди смещение не задается пользователем и программно равно всегда половине диаметра инструмента.

**Comment by XRay3D** [comment]
Если так боитесь, то можете добить профилем поверху или снаружи.
