### ISSUE TITLE
УП Профиль обрезка платы создает код как внутри profile так и снаружи

### ISSUE THREAD

**Issue by neurotoxin78** [XRay3D/GERBER_X3#74]
При попытке создать УП для обрезки платы по контуру (profile.gbr) правильно создается код, только если выбрать Поверху.  Если же выбрать снаружи получается как на скрине
![ggeasy_bug](https://user-images.githubusercontent.com/6095590/153070419-7de38893-1758-4d48-b228-fb00439ed29b.png)
.

**Comment by RomSunZ** [comment]
Измените тип гербер файла с "нормальный" на "пути апертуры"
