### ISSUE TITLE
NMAKE : fatal error U1073: Don't know how to generate “static_libs\gi\CMakeFiles\gi.dir\cmake_pch.cxx.pch”

### ISSUE THREAD

**Issue by jhhe66** [XRay3D/GERBER_X3#84]
NMAKE : fatal error U1073: Don't know how to generate “static_libs\gi\CMakeFiles\gi.dir\cmake_pch.cxx.pch”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\nmake.exe"”: return code “0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\nmake.exe"”: return code “0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\nmake.exe"”: return code “0x2”
Stop.

**Comment by XRay3D** [comment]
I am building a project from under Qt Creator. I don't do any additional settings.
