### ISSUE TITLE
При экспорте из DipTrace файла сверловки изображение сверловки становится больших размеров. Ошибка.

### ISSUE THREAD

**Issue by Pank172** [XRay3D/GERBER_X3#89]
Versions

GGEasy version: 0.8.1.0 
PC info

OS: Windows 10 x64
CPU: AMD Ryzen 3600
RAM: 16Gb
DirectX 12 at Radeon RX570
Разрешение экрана 1920х1080

Использую программу Diptrace 4.3.0.1.
При переносе в программу  файла сверловки из Diptrace размер отверстий стает больше размера платы в 50 раз.

**Comment by XRay3D** [comment]
Можете прикрепить файл или привести текст файла сверловок.

**Comment by Pank172** [comment]
Да конечно
[444-1-2_gerber.zip](https://github.com/XRay3D/GERBER_X3/files/9928266/444-1-2_gerber.zip)

**Comment by Pank172** [comment]
Размер сверловки в 10 раз превышает размеры платы. Размер платы 95Х105 мм, а размер сверловки 950Х1050мм. Как побороть?

**Comment by Pank172** [comment]
Разобрался. Установил соотношение 1:2 в настройках файла сверловки. Единицы - миллиметры, нули - ведущие, формат - 1:2, смещение Х-0,0000, У - 0,0000. коэффициент - х10.

**Comment by Pank172** [comment]
Спасибо за классную программу.
