### ISSUE TITLE
Лазер вместо фрезы

### ISSUE THREAD

**Issue by AkyJlenok** [XRay3D/GERBER_X3#90]
В программе предусмотрен выбор лазера, однако я не понимаю, как пересчитать обороты в минуту в мощность лазера :disappointed:

**Comment by YuryW** [comment]
Привет, AkyJlenok
Посмотри здесь https://cnc3018.ru/threads/ggeasy-grber2gcode-frezerovka-pechatnyx-plat-na-chpu-zasvetka-lazerom-izuchaem-delimsja-opytom-i-dostizhenijami.2231/page-20#post-55773
С уважением, YuryW
