### ISSUE TITLE
Вопрос по 0.9.0b

### ISSUE THREAD

**Issue by ivan64435** [XRay3D/GERBER_X3#94]
где можно скачать 32 битную версию?

**Comment by XRay3D** [comment]
Собрать)

**Comment by kpbicka** [comment]
> Собрать) Я удивлён что х32 в ходу, оно же медленнее в 1.5, а скорее в 2 раза. https://disk.yandex.ru/d/2SgsV7DGvDQn5w

Ссылка не найдена
